global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "sfu-server"
    metrics_path: /metrics
    static_configs:
      - targets: ["sfu:8081"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]